name: WeChat Spider

on:
  schedule:
    - cron: '0 0,4,8,10,12 * * *'  # UTC 时间，对应北京时间 8,10,12,14,16,18,20,22
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run spider
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: python main.py